### ISSUE TITLE
I/O error with mount involving symlinks

### ISSUE THREAD

**Issue by kalikiana** [CanonicalLtd/multipass#81]
> multipass launch --name=foo
    > git clone https://github.com/LaughingLove/branch-diff-snap.git
    > cd branch-diff-snap
    > multipass mount . foo
    > pwd
    /home/cris/bau/branch-diff-snap
    > multipass connect foo
    $ cd /home/cris/bau/branch-diff-snap
    $ sudo snap install snapcraft --classic --edge
    $ $ snapcraft
    Installing build dependencies: libc-dev-bin libc6-dev linux-libc-dev manpages-dev zlib1g-dev
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Suggested packages:
      glibc-doc
    The following NEW packages will be installed:
      libc-dev-bin libc6-dev linux-libc-dev manpages-dev zlib1g-dev
    0 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
    Need to get 5,188 kB of archives.
    After this operation, 22.5 MB of additional disk space will be used.
    Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libc-dev-bin amd64 2.23-0ubuntu10 [68.7 kB]
    [...]
    Get:1 liberror-perl_0.17-1.2_all.deb [19.6 kB]                                            
    Fetched 19.6 kB in 0s (0 B/s)                                                             
    Traceback (most recent call last):
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2205, in makelink
        os.symlink(tarinfo.linkname, targetpath)
    OSError: [Errno 5] Input/output error: '6' -> '/home/cris/bau/branch-diff-snap/parts/branch-diff/install/./usr/lib/gcc/x86_64-linux-gnu/6.0.0'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/snap/snapcraft/1069/bin/snapcraft", line 11, in <module>
        load_entry_point('snapcraft==2.38', 'console_scripts', 'snapcraft')()
      File "/snap/snapcraft/1069/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/snap/snapcraft/1069/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
        return ep.load()
      File "/snap/snapcraft/1069/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
        return self.resolve()
      File "/snap/snapcraft/1069/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/cli/__main__.py", line 19, in <module>
        run(prog_name='snapcraft')
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
        return Command.invoke(self, ctx)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/cli/_runner.py", line 72, in run
        ctx.forward(lifecyclecli.commands['snap'])
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 553, in forward
        return self.invoke(cmd, **kwargs)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 139, in snap
        project_options, directory=directory, output=output)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_packer.py", line 45, in snap
        execute('prime', project_options)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 79, in execute
        _Executor(config, project_options).run(step, part_names)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 184, in run
        self._run_step(step, part, part_names)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 214, in _run_step
        getattr(part, 'prepare_{}'.format(step))()
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 266, in prepare_pull
        self._unpack_stage_packages()
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 260, in _unpack_stage_packages
        self._stage_packages_repo.unpack(self.installdir)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 375, in unpack
        unpackdir, src=pkg, clean_target=False, keep_deb=True)
      File "/snap/snapcraft/1069/lib/python3.6/site-packages/snapcraft/internal/sources/_deb.py", line 67, in provision
        tar.extractall(dst)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2003, in extractall
        numeric_owner=numeric_owner)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2045, in extract
        numeric_owner=numeric_owner)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2123, in _extract_member
        self.makelink(tarinfo, targetpath)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2216, in makelink
        targetpath)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2117, in _extract_member
        self.makedir(tarinfo, targetpath)
      File "/snap/snapcraft/1069/usr/lib/python3.6/tarfile.py", line 2146, in makedir
        os.mkdir(targetpath, 0o700)
    OSError: [Errno 5] Input/output error: '/home/cris/bau/branch-diff-snap/parts/branch-diff/install/./usr/lib/gcc/x86_64-linux-gnu/6.0.0'

**Comment by townsend2010** [comment]
Oh, you used '.' as the source path which is a bug in and off itself.  See #84.  I wonder if it would work better if you used $PWD since that will expand to an absolute path.

**Comment by townsend2010** [comment]
Also, if you don't specify a source path after the VM name, like you did, it will use *exactly* what is used for the source path, which may not be what you expect.

For example, since '.' is a bug, it will trying to mount use '.' in the ubuntu user's home in the VM.  Not what you really want.  Also, if you use $PWD, it will mount to /home/cris/bau/branch-diff-snap in the VM which is probably not what you want either.

I would suggest being very specific for mounts, like use something like the following:

``$ multipass mount $PWD foo:bau/branch-diff-snap``

**Comment by kalikiana** [comment]
@townsend2010 Unfortunately the way I mount makes no difference here. With your "very specific" command it fails exactly the same way (except for the path being `/home/ubuntu/bau`).

**Comment by townsend2010** [comment]
@kalikiana Oh well, it was worth a try.  I'll have a look soon.  Thanks!

**Comment by townsend2010** [comment]
If I go and look at the link on the host filesystem, it shows it's owned by root?

```
townsend@Slave1:~/branch-diff-snap/parts/branch-diff/install/usr/lib/gcc/x86_64-linux-gnu$ ls -la
total 12
drwx------ 3 townsend townsend 4096 Feb  1 11:39 .
drwx------ 3 townsend townsend 4096 Feb  1 11:39 ..
drwx------ 2 townsend townsend 4096 Feb  1 11:39 6
lrwxrwxrwx 1 root     root        1 Feb  1 11:39 6.0.0 -> 6
```

Not sure why the link is being owned by root, but I'm suspecting that permissions from the host is messing this up??  Still need to investigate, but thought I'd mention the interesting data point.

**Comment by townsend2010** [comment]
I'm still trying to dig into this.  I think the root owned link on the host is a red herring.  I've dumped sshfs and fuse debug info and added debug to our sftp server code and I still can't figure out what is returning EIO.  Will keep digging...

**Comment by townsend2010** [comment]
Ok, I've finally have found the root cause.  In the handling of file stats, I'm using QFileInfo::{isDir()|isFile()|isSymLink()} to determine the type of file to set in the sftp attributes.  I did not if/else those checks, assuming only one type would be set in QFileInfo.  I was wrong:)  If the file is a symlink, isDir() or isFile() will also be set depending on what the linked file type is, so I would be setting the file as a dir/file and symlink at the same time, which of course would freak things out.

I'll be putting up a PR soon, but please note that the ``snapcraft`` operation is very, VERY slow due to poor performance of the mount.  We are looking into how to increase mount performance, but that is going to be addressed later.
